### ISSUE TITLE
No errors reported if JSON files don't parse

### ISSUE THREAD

**Issue by sazzer** [tandrewnichols/task-master#1]
I've just discovered that, when using JSON configuration files, if the JSON file is malformed then no errors are reported and the system just acts as if it was empty.

**Comment by tandrewnichols** [comment]
Yes . . . that doesn't seem right does it. Well . . . maybe it should proceed with an empty object as it does now, but report the error? Or are you thinking it should blow up and stop?

**Comment by sazzer** [comment]
At the very least it should obviously report the error. Actually failing
would be even more obvious though, but I don't know if that might break any
existing builds...

**Comment by tandrewnichols** [comment]
Seems safe to rethrow, as whatever you were intending to happen wouldn't happen anyway if the file is malformatted. I.e. the build should already be broken if you've got invalid json.

**Comment by sazzer** [comment]
Works for me :-)

**Comment by tandrewnichols** [comment]
@sazzer See #2. Most of the changes are just updating dependencies, etc. The specific change for this issue is here: https://github.com/tandrewnichols/task-master/blob/22838193f0ef0386986e40c3f5300dc2a013c9a1/lib/loader.js#L17-L22

**Comment by tandrewnichols** [comment]
Closed via #2

**Comment by tandrewnichols** [comment]
@sazzer Published as v2.3.0

**Comment by sazzer** [comment]
Awesome. Thank you
